//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_serialization.py
// Do not edit this file manually, your changes will be overwritten
//===----------------------------------------------------------------------===//

#include "duckdb/common/serializer/serializer.hpp"
#include "duckdb/common/serializer/deserializer.hpp"
#include "quack_message.hpp"

namespace duckdb {

void AcknowledgementMessage::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<hugeint_t>(1, "query_uuid", query_uuid, hugeint_t(0, 0));
}

unique_ptr<AcknowledgementMessage> AcknowledgementMessage::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<AcknowledgementMessage>(new AcknowledgementMessage());
	deserializer.ReadPropertyWithExplicitDefault<hugeint_t>(1, "query_uuid", result->query_uuid, hugeint_t(0, 0));
	return result;
}

void CancelRequestMessage::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<hugeint_t>(1, "query_uuid", query_uuid);
}

unique_ptr<CancelRequestMessage> CancelRequestMessage::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<CancelRequestMessage>(new CancelRequestMessage());
	deserializer.ReadProperty<hugeint_t>(1, "query_uuid", result->query_uuid);
	return result;
}

void ConnectionRequestMessage::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<string>(1, "auth_string", auth_string);
	serializer.WritePropertyWithDefault<string>(2, "client_duckdb_version", client_duckdb_version);
	serializer.WritePropertyWithDefault<string>(3, "client_platform", client_platform);
	serializer.WritePropertyWithDefault<idx_t>(4, "min_supported_quack_version", min_supported_quack_version);
	serializer.WritePropertyWithDefault<idx_t>(5, "max_supported_quack_version", max_supported_quack_version);
	serializer.WritePropertyWithDefault<string>(6, "client_id", client_id);
	serializer.WritePropertyWithDefault<idx_t>(7, "heartbeat_timeout_seconds", heartbeat_timeout_seconds);
}

unique_ptr<ConnectionRequestMessage> ConnectionRequestMessage::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<ConnectionRequestMessage>(new ConnectionRequestMessage());
	deserializer.ReadPropertyWithDefault<string>(1, "auth_string", result->auth_string);
	deserializer.ReadPropertyWithDefault<string>(2, "client_duckdb_version", result->client_duckdb_version);
	deserializer.ReadPropertyWithDefault<string>(3, "client_platform", result->client_platform);
	deserializer.ReadPropertyWithDefault<idx_t>(4, "min_supported_quack_version", result->min_supported_quack_version);
	deserializer.ReadPropertyWithDefault<idx_t>(5, "max_supported_quack_version", result->max_supported_quack_version);
	deserializer.ReadPropertyWithDefault<string>(6, "client_id", result->client_id);
	deserializer.ReadPropertyWithDefault<idx_t>(7, "heartbeat_timeout_seconds", result->heartbeat_timeout_seconds);
	return result;
}

void ConnectionResponseMessage::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<string>(1, "server_duckdb_version", server_duckdb_version);
	serializer.WritePropertyWithDefault<string>(2, "server_platform", server_platform);
	serializer.WritePropertyWithDefault<idx_t>(3, "quack_version", quack_version);
	serializer.WritePropertyWithDefault<idx_t>(4, "heartbeat_timeout_seconds", heartbeat_timeout_seconds);
}

unique_ptr<ConnectionResponseMessage> ConnectionResponseMessage::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<ConnectionResponseMessage>(new ConnectionResponseMessage());
	deserializer.ReadPropertyWithDefault<string>(1, "server_duckdb_version", result->server_duckdb_version);
	deserializer.ReadPropertyWithDefault<string>(2, "server_platform", result->server_platform);
	deserializer.ReadPropertyWithDefault<idx_t>(3, "quack_version", result->quack_version);
	deserializer.ReadPropertyWithDefault<idx_t>(4, "heartbeat_timeout_seconds", result->heartbeat_timeout_seconds);
	return result;
}

void DisconnectMessage::Serialize(Serializer &serializer) const {
}

unique_ptr<DisconnectMessage> DisconnectMessage::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<DisconnectMessage>(new DisconnectMessage());
	return result;
}

void ErrorResponse::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<string>(1, "message", error.RawMessage());
}

unique_ptr<ErrorResponse> ErrorResponse::Deserialize(Deserializer &deserializer) {
	auto message = deserializer.ReadPropertyWithDefault<string>(1, "message");
	auto result = duckdb::unique_ptr<ErrorResponse>(new ErrorResponse(std::move(message)));
	return result;
}

void FetchRequestMessage::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<hugeint_t>(1, "uuid", uuid);
	serializer.WritePropertyWithDefault<idx_t>(2, "batch_index", batch_index, 0);
	serializer.WritePropertyWithDefault<idx_t>(3, "ack_index", ack_index, 0);
}

unique_ptr<FetchRequestMessage> FetchRequestMessage::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<FetchRequestMessage>(new FetchRequestMessage());
	deserializer.ReadProperty<hugeint_t>(1, "uuid", result->uuid);
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(2, "batch_index", result->batch_index, 0);
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(3, "ack_index", result->ack_index, 0);
	return result;
}

void FetchResponseMessage::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<idx_t>(1, "chunk_count", chunk_count, 0);
	serializer.WritePropertyWithDefault<optional_idx>(2, "total_batches", total_batches, optional_idx());
	serializer.WritePropertyWithDefault<optional_idx>(3, "batch_index", batch_index, optional_idx());
}

unique_ptr<FetchResponseMessage> FetchResponseMessage::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<FetchResponseMessage>(new FetchResponseMessage());
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(1, "chunk_count", result->chunk_count, 0);
	deserializer.ReadPropertyWithExplicitDefault<optional_idx>(2, "total_batches", result->total_batches,
	                                                           optional_idx());
	deserializer.ReadPropertyWithExplicitDefault<optional_idx>(3, "batch_index", result->batch_index, optional_idx());
	return result;
}

void HeartbeatRequestMessage::Serialize(Serializer &serializer) const {
}

unique_ptr<HeartbeatRequestMessage> HeartbeatRequestMessage::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<HeartbeatRequestMessage>(new HeartbeatRequestMessage());
	return result;
}

void MessageHeader::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<MessageType>(1, "type", type);
	serializer.WritePropertyWithDefault<string>(2, "connection_id", connection_id);
	serializer.WriteProperty<optional_idx>(3, "client_query_id", client_query_id);
}

MessageHeader MessageHeader::Deserialize(Deserializer &deserializer) {
	auto type = deserializer.ReadProperty<MessageType>(1, "type");
	auto connection_id = deserializer.ReadPropertyWithDefault<string>(2, "connection_id");
	MessageHeader result(type, std::move(connection_id));
	deserializer.ReadProperty<optional_idx>(3, "client_query_id", result.client_query_id);
	return result;
}

void PrepareRequestMessage::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<string>(1, "sql_query", sql_query);
	serializer.WriteProperty<hugeint_t>(2, "query_uuid", query_uuid);
	serializer.WritePropertyWithDefault<optional_idx>(3, "inline_rows", inline_rows, optional_idx());
}

unique_ptr<PrepareRequestMessage> PrepareRequestMessage::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<PrepareRequestMessage>(new PrepareRequestMessage());
	deserializer.ReadPropertyWithDefault<string>(1, "sql_query", result->sql_query);
	deserializer.ReadProperty<hugeint_t>(2, "query_uuid", result->query_uuid);
	deserializer.ReadPropertyWithExplicitDefault<optional_idx>(3, "inline_rows", result->inline_rows, optional_idx());
	return result;
}

void PrepareResponseMessage::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<vector<LogicalType>>(1, "result_types", result_types);
	serializer.WritePropertyWithDefault<vector<string>>(2, "result_names", result_names);
	serializer.WritePropertyWithDefault<bool>(3, "needs_more_fetch", needs_more_fetch);
	serializer.WritePropertyWithDefault<vector<unique_ptr<DataChunkWrapper>>>(4, "results", results);
	serializer.WriteProperty<hugeint_t>(5, "query_uuid", query_uuid);
}

unique_ptr<PrepareResponseMessage> PrepareResponseMessage::Deserialize(Deserializer &deserializer) {
	auto result_types = deserializer.ReadPropertyWithDefault<vector<LogicalType>>(1, "result_types");
	auto result_names = deserializer.ReadPropertyWithDefault<vector<string>>(2, "result_names");
	auto needs_more_fetch = deserializer.ReadPropertyWithDefault<bool>(3, "needs_more_fetch");
	auto results = deserializer.ReadPropertyWithDefault<vector<unique_ptr<DataChunkWrapper>>>(4, "results");
	auto query_uuid = deserializer.ReadProperty<hugeint_t>(5, "query_uuid");
	auto result = duckdb::unique_ptr<PrepareResponseMessage>(new PrepareResponseMessage(
	    std::move(result_types), std::move(result_names), std::move(results), needs_more_fetch, query_uuid));
	return result;
}

void SendDataRequestMessage::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<string>(1, "stream_id", stream_id);
	serializer.WritePropertyWithDefault<idx_t>(2, "chunk_count", chunk_count, 0);
	serializer.WritePropertyWithDefault<optional_idx>(3, "total_batches", total_batches, optional_idx());
	serializer.WritePropertyWithDefault<optional_idx>(4, "batch_index", batch_index, optional_idx());
}

unique_ptr<SendDataRequestMessage> SendDataRequestMessage::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<SendDataRequestMessage>(new SendDataRequestMessage());
	deserializer.ReadPropertyWithDefault<string>(1, "stream_id", result->stream_id);
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(2, "chunk_count", result->chunk_count, 0);
	deserializer.ReadPropertyWithExplicitDefault<optional_idx>(3, "total_batches", result->total_batches,
	                                                           optional_idx());
	deserializer.ReadPropertyWithExplicitDefault<optional_idx>(4, "batch_index", result->batch_index, optional_idx());
	return result;
}

void SendDataResponseMessage::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<optional_idx>(1, "accept_budget", accept_budget);
}

unique_ptr<SendDataResponseMessage> SendDataResponseMessage::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<SendDataResponseMessage>(new SendDataResponseMessage());
	deserializer.ReadProperty<optional_idx>(1, "accept_budget", result->accept_budget);
	return result;
}

void SuccessResponse::Serialize(Serializer &serializer) const {
}

unique_ptr<SuccessResponse> SuccessResponse::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<SuccessResponse>(new SuccessResponse());
	return result;
}

} // namespace duckdb
